version: '3'
services: 
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build: .
    ports: 
      - "8081:8081"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379